# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bd68cdad3c65c58fe649b8c958df05776d547ec10382f5529c2b540dde19843de10c03bc856b6e01a5395119a6dcbed2f23a438e19ed60f9889474338952682

test:
  secret_key_base: 0bafc7aabeb0e28ebb94b907947f7705495f24077b9ebee608ecf9df147f799057f2238fd87949271ea9ae7f5d6bf090db5b71f89c1f9cb8245c8cb2defd7629

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
